global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'rss_feeder'
    static_configs:
      - targets: ['app:8000']
    metrics_path: '/metrics'

  - job_name: 'kafka_exporter'
    static_configs:
      - targets: ['kafka-exporter:9308']
