apiVersion: v1
kind: Service
metadata:
  name: rss-aggregator
  labels:
    app: rss-aggregator
spec:
  selector:
    app: rss-aggregator
  ports:
  - port: 8000
    targetPort: http
    name: http
  type: ClusterIP
